name: Onboarding to Open Austin
description: Use this template when joining the Design community of practice to get a checklist of tasks to self-onboard.
title:  "{Name}: Onboarding Tasks "
labels: [ ]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
    value: |
      # Welcome to Open Austin Onboarding
      Welcome text here
  - type: textarea
    id: checklist
    attributes:
      label: Onboarding Checklist
      description: "Leave this as is, this will just be your starting checklist to use to follow along with for onboarding."
      value: |
        - [ ] example task
        - [ ] example task
        - [ ] example task
        - [ ] example task
    validations:
      required: true
